print("Hello world")
print("Hello Again")
print("I like typing this")
print("This is a lot of Fun")
print("Yaya!!! Printing")
print('Zed is so stupid')
print("I'd rather think you 'not'")
print('I "said" do not touch this!!')
